version: '3'
services:
  minio:
    image: minio/minio
    container_name: minio
    restart: always
    network_mode: host
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    volumes:
      - /home/minio/data:/data
      - /home/minio/config:/root/.minio
    command: server /data --console-address ":9090" --address ":9000"
  redis-test:
    image: redis
    container_name: redis-test
    restart: always
    ports:
      - "6379:6379"
    stdin_open: true
    tty: true
    detach: true
    